import Head from 'next/head';
import Header from '../componets/Header';
import Main from '../componets/Main';
import SecondSection from '@/componets/SecondSection';
import SecessionDishes from '@/componets/SecessionDishes';

export default function Home() {
  return (
    <>
      <Head>
        <title>FoodJP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Main />
      <SecondSection />
      <SecessionDishes />
    </>
  );
}
