import Head from 'next/head';
import Header from '../componets/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>FoodJP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <h1>test</h1>
    </>
  );
}
